
version: "3"
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5431:5432
  produto-db:
      image: postgres:11
      container_name: produto-db
      restart: always
      environment:
        - POSTGRES_DB=produto_db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=123456
      ports:
        - 5433:5432
  seles-db:
    image: tutum/mongodb
    container_name: seles-db
    restart: always
    environment:
      - MONGODB_USER=admin
      - MONGODB_DATABASE=sales
      - MONGODB_PASS=123456
    ports:
      - 27017:27017
      - 28017:28017
  

  sales-api:
    build: './sales-api'
    container_name: sales-api
    environment:
      - PORT=8082
    ports:
      - 8082:8082    

  produto-api:
    build: './produto-api'
    container_name: produto-api
    environment:
      - PORT=8081
    ports:
      - 8081:8081    
      
  auth-api:
    build: './auth-api'
    container_name: auth-api
    environment:
      - PORT=8080
    ports:
      - 8080:8080
      
      
  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
